Rr.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Rr.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Rr.Web/Pages/HttpMonitors/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rr.Core.Data;

namespace Rr.Web.Pages.HttpMonitors;

public class CreateModel(IDb db) : PageModel
{
    [BindProperty]
    public HttpMonitor HttpMonitor { get; set; } = new();

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        db.HttpMonitors.Add(HttpMonitor);
        await db.SaveChangesAsync();

        return RedirectToPage("./Index");
    }
}

Rr.Web/Pages/HttpMonitors/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rr.Core.Data;

namespace Rr.Web.Pages.HttpMonitors;

public class EditModel(IDb db) 
    : PageModel
{
    [BindProperty]
    public HttpMonitor? HttpMonitor { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        if (id == null)
            return NotFound();

        HttpMonitor = await db.HttpMonitors.FirstOrDefaultAsync(m => m.Id == id);

        if (HttpMonitor == null)
            return NotFound();

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        if (HttpMonitor != null)
        {
            db.AttachModified(HttpMonitor);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!db.HttpMonitors.Any(e => e.Id == HttpMonitor.Id))
                    return NotFound();

                throw;
            }
        }

        return RedirectToPage("./Index");
    }
}

Rr.Web/Pages/HttpMonitors/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rr.Core.Data;
using Rr.Core.Services;

namespace Rr.Web.Pages.HttpMonitors;

public class IndexModel(IDb db, IMonitorService monitorService) : PageModel
{
    public HttpMonitor[] HttpMonitors { get; set; } = Array.Empty<HttpMonitor>();

    public async Task OnGetAsync()
    {
        HttpMonitors = await db.HttpMonitors
            .OrderByDescending(x => x.CheckedAt != default && (x.Status == 0 || x.Status >= 300))
            .ThenBy(x => x.Name)
            .ToArrayAsync();
    }

    public async Task<IActionResult> OnPostCheckAllUrlsAsync()
    {
        await monitorService.CheckUrlsAsync();
        
        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostCheckUrlAsync(int id)
    {
        await monitorService.CheckUrlAsync(id);

        return RedirectToPage();
    }
    
    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {
        HttpMonitor? monitor = await db.HttpMonitors.FindAsync(id);

        if (monitor != null)
        {
            db.HttpMonitors.Remove(monitor);
            await db.SaveChangesAsync();
        }

        return RedirectToPage();
    }
}

Rr.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Rr.Core.Data;

namespace Rr.Web.Pages;

public class IndexModel : PageModel
{
    public IActionResult OnGet()
    {
        return RedirectToPage("./HttpMonitors/Index");
    }
}

Rr.Web/Pages/HttpMonitors/Create.cshtml
@page
@using Rr.Core.Data
@model Rr.Web.Pages.HttpMonitors.CreateModel

@{
    ViewData["Title"] = "Create Http monitor";
}

<h1>@ViewData["Title"]</h1>

<form method="post">
    <div asp-validation-summary="ModelOnly" class="mb-3 text-danger"></div>

    <div class="mb-3">
        <label for="@nameof(HttpMonitor.Name)" class="form-label">Name</label>
        <input asp-for="HttpMonitor.Name" id="@nameof(HttpMonitor.Name)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor.Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <div class="form-check form-switch">
            <input asp-for="HttpMonitor.IsEnabled" id="@nameof(HttpMonitor.IsEnabled)" class="form-check-input" type="checkbox" role="switch">
            <label class="form-check-label" for="@nameof(HttpMonitor.IsEnabled)">Is enabled</label>
        </div>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.Url)" class="form-label">URL</label>
        <input asp-for="HttpMonitor.Url" id="@nameof(HttpMonitor.Url)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor.Url" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.TimeoutMs)" class="form-label">Timeout (ms)</label>
        <input asp-for="HttpMonitor.TimeoutMs" id="@nameof(HttpMonitor.TimeoutMs)" type="number" class="form-control"/>
        <span asp-validation-for="HttpMonitor.TimeoutMs" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.ContentContains)" class="form-label">Content contains</label>
        <input asp-for="HttpMonitor.ContentContains" id="@nameof(HttpMonitor.ContentContains)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor.ContentContains" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.ContentNotContains)" class="form-label">Content not contains</label>
        <input asp-for="HttpMonitor.ContentNotContains" id="@nameof(HttpMonitor.ContentNotContains)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor.ContentNotContains" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Rr.Web/Pages/HttpMonitors/Edit.cshtml
@page "{id:int}"
@using Rr.Core.Data
@model Rr.Web.Pages.HttpMonitors.EditModel

@{
    ViewData["Title"] = "Edit Http monitor";
}

<h1>@ViewData["Title"]</h1>

<form method="post">
    <input type="hidden" asp-for="HttpMonitor!.Id"/>

    <div asp-validation-summary="ModelOnly" class="mb-3 text-danger"></div>

    <div class="mb-3">
        <label for="@nameof(HttpMonitor.Name)" class="form-label">Name</label>
        <input asp-for="HttpMonitor!.Name" id="@nameof(HttpMonitor.Name)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor!.Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <div class="form-check form-switch">
            <input asp-for="HttpMonitor!.IsEnabled" id="@nameof(HttpMonitor.IsEnabled)" class="form-check-input" type="checkbox" role="switch">
            <label class="form-check-label" for="@nameof(HttpMonitor.IsEnabled)">Is enabled</label>
        </div>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.Url)" class="form-label">URL</label>
        <input asp-for="HttpMonitor!.Url" id="@nameof(HttpMonitor.Url)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor!.Url" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.TimeoutMs)" class="form-label">Timeout (ms)</label>
        <input asp-for="HttpMonitor!.TimeoutMs" id="@nameof(HttpMonitor.TimeoutMs)" type="number" class="form-control"/>
        <span asp-validation-for="HttpMonitor!.TimeoutMs" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.ContentContains)" class="form-label">Content contains</label>
        <input asp-for="HttpMonitor!.ContentContains" id="@nameof(HttpMonitor.ContentContains)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor!.ContentContains" class="text-danger"></span>
        <div class="form-text">Notify when request content contains text.</div>
    </div>
    <div class="mb-3">
        <label for="@nameof(HttpMonitor.ContentNotContains)" class="form-label">Content not contains</label>
        <input asp-for="HttpMonitor!.ContentNotContains" id="@nameof(HttpMonitor.ContentNotContains)" type="text" class="form-control"/>
        <span asp-validation-for="HttpMonitor!.ContentNotContains" class="text-danger"></span>
        <div class="form-text">Notify when request content not contains text.</div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Rr.Web/Pages/HttpMonitors/Index.cshtml
@page
@using Rr.Core.Data
@model Rr.Web.Pages.HttpMonitors.IndexModel
@{
    ViewData["Title"] = "Http monitors";

    string GetRowStatus(HttpMonitor monitor)
    {
        if (monitor.CheckedAt != default && monitor.Status is 0 or >= 400) 
            return "table-danger";
        if (monitor.TimeoutMs > 0 && monitor.ResponseTimeMs > monitor.TimeoutMs)
            return "table-warning";

        return "";
    }
}

<form method="post">
    <div class="row">
        <div class="col">
            <h1>@ViewData["Title"]</h1>
        </div>
        <div class="col d-flex justify-content-end align-items-center">
            <div>
                <button type="submit" asp-page-handler="checkAllUrls" class="btn btn-secondary btn-sm">Check all urls</button>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
        <th>Id</th>
        <th>Name</th>
        <th>Url</th>
        <th>Checked at</th>
        <th>Status</th>
        <th>Time (ms)</th>
        <th></th>
        </thead>
        <tbody>
        @foreach (HttpMonitor monitor in Model.HttpMonitors)
        {
            <tr class="@GetRowStatus(monitor)">
                <td>@monitor.Id</td>
                <td>
                    @if (monitor.IsEnabled)
                    {
                        @monitor.Name
                    }
                    else
                    {
                        <del>@monitor.Name</del>
                    }
                </td>
                <td>
                    <a href="@monitor.Url" target="_blank">@monitor.Url</a>
                </td>
                <td>@(monitor.CheckedAt != default ? monitor.CheckedAt.ToLocalTime() : "")</td>
                <td>@(monitor.CheckedAt != default ? monitor.Status : "")</td>
                <td>@(monitor.CheckedAt != default ? monitor.ResponseTimeMs : "")</td>
                <td style="white-space:nowrap">
                    <button type="submit" asp-page-handler="checkUrl" asp-route-id="@monitor.Id" class="btn btn-secondary btn-sm">Check url</button>
                    <a asp-page="./Edit" asp-route-id="@monitor.Id" class="btn btn-primary btn-sm">Edit</a>
                    <button type="submit" asp-page-handler="delete" asp-route-id="@monitor.Id" class="btn btn-danger btn-sm">Delete</button>
                </td>
            </tr>
        }
        </tbody>
    </table>
</form>

Rr.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rr.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ResponseRadar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">ResponseRadar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-page="/HttpMonitors/Index">Http monitors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-page="/HttpMonitors/Create">Create</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>